name: APP_NAME
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure AWS Creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: nextjs-app
        IMAGE_TAG: latest
      run: |
        docker build --build-arg APP_VERSION=${{ secrets.APP_VERSION }} --build-arg S3_PATH=${{ secrets.S3_PATH }} --build-arg AWS_DEFAULT_REGION=${{ env.AWS_DEFAULT_REGION }} --build-arg AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY_ID }} --build-arg AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS_KEY }} -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }} .
        docker push --all-tags $ECR_REGISTRY/$ECR_REPOSITORY
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Deploying Latest code to ECS
        run : |
          sudo apt-get install jq -y
          jq --version
          aws ecs describe-task-definition --task-definition App-test > task-def.json
          jq .taskDefinition task-def.json > taskdefinition.json
          jq 'del(.taskDefinitionArn)' taskdefinition.json | jq 'del(.revision)' | jq 'del(.status)' | jq 'del(.requiresAttributes)' | jq 'del(.compatibilities)' | jq 'del(.registeredAt)'| jq 'del(.registeredBy)' > container-definition.json
          aws ecs register-task-definition --cli-input-json file://container-definition.json  
          aws ecs update-service --cluster Nextjs-cluster --service my-sv --task-definition App-test